runserver:
	- python3 manage.py runserver

makemigrations:
	- python3 manage.py makemigrations

migrate:
	- python3 manage.py migrate

add .:
	- git add .

push:
	- git push .

test:
	- python3 manage.py test

