# Generated by Django 4.0 on 2021-12-26 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attachment',
            field=models.FileField(null=True, upload_to='attachments'),
        ),
    ]
