# Generated by Django 4.0 on 2021-12-27 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_postreaction_reaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreaction',
            name='reaction',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
