# Generated by Django 4.0 on 2021-12-27 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_postreaction_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='postreaction',
            name='test',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
