# Generated by Django 4.0 on 2021-12-27 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0013_postreaction_test"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postreaction",
            name="test",
        ),
    ]
